name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
      - name: Check copyright
        uses: sigma/addlicense@master
      - name: Run build
        run: go build ./...
      - name: Run testing
        run: go test -v ./...
